### ISSUE TITLE
Implement Typespec tests

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/supported-networks#6]
## Tasks
- [ ] Validate the JSON based on the Typespec definitions
- [ ] Ideally we don't add any Javascript dependencies
- [ ] Investigate how to leverage Typespec CLI to validate against JSON
- [ ] use `TypeSpec.JsonSchema` https://typespec.io/data-validation

## Typespec types:
- [ ] `blocks`
- [ ] `chains`
- [ ] `icons`
- [ ] `providers`

**Comment by YaroShkvorets** [comment]
Replaced with json-schema validation in #21
